# Generated by Django 4.2.6 on 2023-10-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0011_remove_product_owner'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
