# Generated by Django 4.2.6 on 2023-10-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0010_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
